### ISSUE TITLE
numpy import doesn't worked for me anymore

### ISSUE THREAD

**Issue by ftemme** [mackaiver/lst_calibration#9]
When I go in the repository folder (lst_calibration), start python and import numpy, it fails with the following error message:
```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/site-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing import Tester
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/unittest/main.py", line 7, in <module>
    from . import loader, runner
  File "/home/fabian/mount/data/LinuxDaten/software/anaconda/lib/python2.7/unittest/runner.py", line 4, in <module>
    import time
  File "time.py", line 2, in <module>
    from dragonboard import read
  File "dragonboard/__init__.py", line 1, in <module>**
    from .io import read, EventGenerator, Event, EventHeader
  File "dragonboard/io.py", line 20, in <module>
    stop_cell_dtype = np.dtype('uint16').newbyteorder('>')
AttributeError: 'module' object has no attribute 'dtype'
```
For me it seems that numpy tries to import a time module and wrongly tries to import the one from the repository. 
Did I mess something up with my python / numpy installation, or should the time module in our repository be renamed?

**Comment by dneise** [comment]
I don't get the same behaviour, but we should never the less rename 
"time.py" --> a meaningful name. I have no clue, what this is supposed to do. 
A docstring in the file header is certainly needed here.

**Comment by dneise** [comment]
I also don't get the first line, what are profilehooks?

**Comment by dneise** [comment]
I neither see the behaviour you described with py2 nor with py3. So I would believe, you kind of messed something up. :-) ... but still, I guess one should avoid filenames like:
time.py, os.py,  sys.py, datetime.py and so on..

**Comment by MaxNoe** [comment]
Sorry, my bad. I used this to identify the reading problem.
